//
// DO NOT EDIT THIS FILE.
// Generated using AndroidAnnotations 4.8.0.
// 
// You can create a larger work that contains this file and distribute that work under terms of your choice.
//

package com.tomclaw.appsend.core;

import android.content.Context;

import com.tomclaw.appsend.di.legacy.LegacyInjector;

import org.androidannotations.api.view.OnViewChangedNotifier;

public final class StoreServiceHolder_
    extends StoreServiceHolder
{
    private Context context_;
    private Object rootFragment_;
    private static StoreServiceHolder_ instance_;

    private StoreServiceHolder_(Context context) {
        context_ = context;
    }

    private StoreServiceHolder_(Context context, Object rootFragment) {
        context_ = context;
        rootFragment_ = rootFragment;
    }

    public static StoreServiceHolder_ getInstance_(Context context) {
        if (instance_ == null) {
            OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(null);
            instance_ = new StoreServiceHolder_(context.getApplicationContext());
            instance_.init_();
            OnViewChangedNotifier.replaceNotifier(previousNotifier);
        }
        return instance_;
    }

    private void init_() {
        this.injector = LegacyInjector.getInstance();
    }
}
